window.KPI_PRODUCTS = [
  {
    "id": 1,
    "name": "Vissticks",
    "brand": "A&B Famous",
    "category": "Vis",
    "variant": "400 g",
    "ingredients": "vis (heek merluccius capensis/paradoxus), paneermeel (tarwebloem, tapiocabloem, zout, dextrose, plantaardige olie, rijsmiddelen natriumbicarbonaat en natriumfosfaat, emulgator monoglyceriden en diglyceriden en xanthaangom), maïsbloem, geel maïsmeel, aardappelzetmeel, zout, cellulose, knoflookpoeder, specerijen. kort voorgebakken in zonnebloemolie.",
    "allergens": [
      "VIS",
      "TARWE"
    ],
    "allergenNote": "",
    "kosher": "OU en CRC (Central Rabbinical Congress)",
    "note": "",
    "image": "./images/01-vissticks.jpg",
    "ean": "732973000083"
  },
  {
    "id": 2,
    "name": "Gepaneerde Tilapianuggets",
    "brand": "A&B Famous",
    "category": "Vis",
    "variant": "400 g",
    "ingredients": "vis (tilapia), paneermeel (tarwebloem, tapiocabloem, zout, dextrose, plantaardige olie, rijsmiddelen natriumbicarbonaat en natriumfosfaat, emulgator monoglyceriden en diglyceriden en xanthaangom), geel maïsmeel, maïszetmeel, aardappelzetmeel, zout, cellulose, knoflookpoeder, specerijen. kort voorgebakken in koolzaadolie.",
    "allergens": [
      "VIS",
      "TARWE"
    ],
    "allergenNote": "",
    "kosher": "OU en CRC (Central Rabbinical Congress)",
    "note": "",
    "image": "./images/02-gepaneerde-tilapianuggets.jpg",
    "ean": "732973000809"
  },
  {
    "id": 3,
    "name": "Tilapiafilets",
    "brand": "A&B Famous",
    "category": "Vis",
    "variant": "400 g",
    "ingredients": "tilapia (vis).",
    "allergens": [
      "VIS",
      "TARWE"
    ],
    "allergenNote": "Allergenen volgens de online productinformatie; nog te controleren op de verpakking.",
    "kosher": "OU en CRC (Central Rabbinical Congress). De getoonde verpakking vermeldt ook geschikt voor Pesach.",
    "note": "",
    "image": "./images/03-tilapiafilets.jpg",
    "ean": "732973000120"
  },
  {
    "id": 4,
    "name": "Gepaneerde Tilapiafilets",
    "brand": "A&B Famous",
    "category": "Vis",
    "variant": "454 g",
    "ingredients": "vis (tilapia), paneermeel (tarwebloem, tapiocabloem, zout, dextrose, plantaardige olie, rijsmiddelen natriumbicarbonaat en natriumfosfaat, emulgator monoglyceriden en diglyceriden en xanthaangom), maïsbloem, maïszetmeel, aardappelzetmeel, zout, guargom, knoflookpoeder, specerijen. voorgebakken in koolzaadolie.",
    "allergens": [
      "VIS",
      "TARWE"
    ],
    "allergenNote": "",
    "kosher": "OU en CRC (Central Rabbinical Congress)",
    "note": "",
    "image": "./images/04-gepaneerde-tilapiafilets.jpg"
  },
  {
    "id": 5,
    "name": "Runderburgers",
    "brand": "Prime Cut",
    "category": "Rundvlees",
    "variant": "4 x 100 g",
    "ingredients": "Rundvlees (85%), ui, water, specerijen (SOJA, SELDERIJ, SULFIETEN), smeltzouten (E450, E451), zuurteregelaars (E500, E516), smaakversterker (E621), aardappelzetmeel.",
    "allergens": [
      "SOJA",
      "SELDERIJ",
      "SULFIETEN"
    ],
    "allergenNote": "Leesbaar op het Prime Cut-etiket.",
    "kosher": "Kedassia",
    "note": "",
    "image": "./images/05-runderburgers.png",
    "ean": "5060199311610"
  },
  {
    "id": 6,
    "name": "Rundergehakt",
    "brand": "Glatt Kosher",
    "category": "Rundvlees",
    "variant": "",
    "ingredients": "Rundergehakt",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Glatt Beth Josef LaMehadrin",
    "note": "",
    "image": "./images/06-rundergehakt.jpg",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 7,
    "name": "Kippenfilet",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam · Rav Wolf",
    "note": "",
    "image": "./images/07-kippenfilet.png",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 8,
    "name": "Kippendrumsticks",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam · Rav Wolf",
    "note": "",
    "image": "./images/08-kippendrumsticks.png",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 9,
    "name": "Kippenvleugels",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam · Rav Wolf",
    "note": "",
    "image": "./images/09-kippenvleugels.png",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 10,
    "name": "Kippendrumettes",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam · Rav Wolf",
    "note": "",
    "image": "./images/10-kippendrumettes.png",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 11,
    "name": "Kippenbillen",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam · Rav Wolf",
    "note": "",
    "image": "./images/11-kippenbillen.png",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 12,
    "name": "Kippendijvlees",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam · Rav Wolf",
    "note": "",
    "image": "./images/12-kippendijvlees.png",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 13,
    "name": "Hele kip",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam · Rav Wolf",
    "note": "",
    "image": "./images/13-hele-kip.png",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 14,
    "name": "Kip schnitzels gesneden",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam · Rav Wolf",
    "note": "Dit product is rauwe, dun gesneden kipfilet, zonder panering of paneermeel.",
    "image": "./images/14-kip-schnitzels-gesneden.png",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 16,
    "name": "Kip gehakt",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam · Rav Wolf",
    "note": "",
    "image": "./images/16-kip-gehakt.png",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 15,
    "name": "Kip karbonade",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam · Rav Wolf",
    "note": "",
    "image": "./images/15-kip-karbonade.png",
    "allergensConfirmedAbsent": true
  }
];
