window.KPI_PRODUCTS = [
  {
    "id": 1,
    "name": "Vissticks",
    "brand": "A&B Famous",
    "category": "Vis",
    "variant": "400 g",
    "ingredients": "VIS (heek: Merluccius capensis/paradoxus), paneermeel (TARWEbloem, tapiocabloem, zout, dextrose, plantaardige olie, rijsmiddelen [natriumbicarbonaat, natriumfosfaat], emulgator [mono- en diglyceriden, xanthaangom]), maïsbloem, geel maïsmeel, aardappelzetmeel, zout, cellulose, knoflookpoeder, specerijen. Kort voorgebakken in zonnebloemolie.",
    "allergens": [
      "VIS",
      "TARWE"
    ],
    "allergenNote": "",
    "kosher": "Nog niet onafhankelijk bevestigd voor deze verpakkingsuitvoering.",
    "note": "",
    "image": "./images/01-vissticks.jpg"
  },
  {
    "id": 2,
    "name": "Gepaneerde Tilapianuggets",
    "brand": "A&B Famous",
    "category": "Vis",
    "variant": "400 g",
    "ingredients": "VIS (tilapia), paneermeel (TARWEbloem, tapiocabloem, zout, dextrose, plantaardige olie, rijsmiddelen [natriumbicarbonaat, natriumfosfaat], emulgator [mono- en diglyceriden, xanthaangom]), geel maïsmeel, maïszetmeel, aardappelzetmeel, zout, cellulose, knoflookpoeder, specerijen. Kort voorgebakken in koolzaadolie.",
    "allergens": [
      "VIS",
      "TARWE"
    ],
    "allergenNote": "",
    "kosher": "OU / parve en CRC zichtbaar op de online verpakking van dit product. Overige zegels nog niet volledig bevestigd.",
    "note": "",
    "image": "./images/02-gepaneerde-tilapianuggets.jpg"
  },
  {
    "id": 3,
    "name": "Tilapiafilets",
    "brand": "A&B Famous",
    "category": "Vis",
    "variant": "400 g",
    "ingredients": "Tilapia (VIS).",
    "allergens": [
      "VIS"
    ],
    "allergenNote": "De online productpagina vermeldt ook tarwe, maar geeft uitsluitend tilapia als ingrediënt op. Deze tegenstrijdigheid moet nog op het etiket worden gecontroleerd.",
    "kosher": "OU-P / parve en CRC zichtbaar op de online verpakking van dit product. De verpakking vermeldt ook geschikt voor Pesach; controle van de actuele verpakking blijft nodig.",
    "note": "",
    "image": "./images/03-tilapiafilets.jpg"
  },
  {
    "id": 4,
    "name": "Gepaneerde Tilapiafilets",
    "brand": "A&B Famous",
    "category": "Vis",
    "variant": "454 g",
    "ingredients": "VIS (tilapia), paneermeel (TARWEbloem, tapiocabloem, zout, dextrose, plantaardige olie, rijsmiddelen [natriumbicarbonaat, natriumfosfaat], emulgator [mono- en diglyceriden, xanthaangom]), maïsbloem, maïszetmeel, aardappelzetmeel, zout, guargom, knoflookpoeder, specerijen. Voorgebakken in koolzaadolie.",
    "allergens": [
      "VIS",
      "TARWE"
    ],
    "allergenNote": "",
    "kosher": "OU / parve, CRC, Pas Yisroel en Yoshon staan op de verpakking. CRC wordt ook vermeld door distributeur Hatov voor de verpakking van 454 g.",
    "note": "",
    "image": "./images/04-gepaneerde-tilapiafilets.jpg"
  },
  {
    "id": 5,
    "name": "Runderburgers",
    "brand": "Prime Cut",
    "category": "Rundvlees",
    "variant": "4 stuks",
    "ingredients": "Nog te controleren: de volledige ingrediëntenlijst en E-nummers zijn niet scherp genoeg leesbaar. Leesbaar is onder meer rundvlees (85%).",
    "allergens": [
      "SOJA",
      "SELDERIJ",
      "SULFIETEN"
    ],
    "allergenNote": "Leesbaar op het Prime Cut-etiket.",
    "kosher": "Kedassia, Londen, volgens distributeur Hatov voor Prime Cut-runderburgers. Nog te bevestigen voor deze verpakkingsuitvoering.",
    "note": "",
    "image": "./images/05-runderburgers.png"
  },
  {
    "id": 6,
    "name": "Rundergehakt",
    "brand": "Kowalczyk",
    "category": "Rundvlees",
    "variant": "",
    "ingredients": "Rundergehakt",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Glatt Beth Josef LaMehadrin",
    "note": "De merk-/leverancierskoppeling van dit gehakt wordt nog gecontroleerd.",
    "image": "./images/06-rundergehakt.jpg",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 7,
    "name": "Kippenfilet",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam - Rav Wolf",
    "note": "",
    "image": "./images/07-kippenfilet.png",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 8,
    "name": "Kippendrumsticks",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam - Rav Wolf",
    "note": "",
    "image": "./images/08-kippendrumsticks.png",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 9,
    "name": "Kippenvleugels",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam - Rav Wolf",
    "note": "",
    "image": "./images/09-kippenvleugels.png",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 10,
    "name": "Kippendrumettes",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam - Rav Wolf",
    "note": "",
    "image": "./images/10-kippendrumettes.png",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 11,
    "name": "Kippenbillen",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam - Rav Wolf",
    "note": "",
    "image": "./images/11-kippenbillen.png",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 12,
    "name": "Kippendijvlees",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam - Rav Wolf",
    "note": "",
    "image": "./images/12-kippendijvlees.png",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 13,
    "name": "Hele kip",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam - Rav Wolf",
    "note": "",
    "image": "./images/13-hele-kip.png",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 14,
    "name": "Kip schnitzels gesneden",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam - Rav Wolf",
    "note": "Dit product is rauwe, dun gesneden kipfilet, zonder panering of paneermeel.",
    "image": "./images/14-kip-schnitzels-gesneden.png",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 16,
    "name": "Kip gehakt",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam - Rav Wolf",
    "note": "",
    "image": "./images/16-kip-gehakt.png",
    "allergensConfirmedAbsent": true
  },
  {
    "id": 15,
    "name": "Kip karbonade",
    "brand": "Kosher Poultry",
    "category": "Kip",
    "variant": "",
    "ingredients": "100% kip",
    "allergens": [],
    "allergenNote": "",
    "kosher": "Badatz Amsterdam - Rav Wolf",
    "note": "",
    "image": "./images/15-kip-karbonade.png",
    "allergensConfirmedAbsent": true
  }
];
