// Transcribed from the supplied labels; website pictures are tracked separately.
const fs = require('node:fs');
const path = require('node:path');
const products = [];
function add(start, end, brand, name, category, variant, ean, ingredients, allergens, mayContain = '', kosher = null, extra = {}) {
  products.push({id:products.length+1, brand, name, category, variant, ean, ingredients, allergens, mayContain, kosher, image:null,
    sourcePhotos:Array.from({length:end-start+1},(_,i)=>start+i).filter(n=>n!==52&&n!==155).map(n=>`${n}.jpg`),
    productInfo:variant?{'Inhoud':variant}:{}, ...extra});
}
const carmitK = 'Rabbinaat Nof HaGalil (Parve)';
const choking = 'Verstikkingsgevaar voor kinderen jonger dan 5 jaar.';
add(1,2,'Carmit Nature','Granola-repen noten & cranberry','Repen','150 g (5 × 30 g)','850047456717','Gemengde noten (30%) (cashewnoten, amandelen, hazelnoten), inuline, geroosterde pinda’s (17%), gepofte volkoren rijst, tahin (hele sesamzaadjes), dadelstroop, pompoenpitten, cranberries (4,5%) (cranberries, appelconcentraat, koolzaadolie), glycerine, natuurlijk aroma (vanille-extract), steviolglycosiden.',['Cashewnoten','Amandelen','Hazelnoten','Pinda’s','Sesam'],'Pecannoten, walnoten, paranoten, macadamianoten, pistachenoten, pijnboompitten, tarwe, soja en mosterd.',carmitK,{warning:choking});
add(3,4,'Carmit Nature','Granola-repen kokos & cashew','Repen','150 g (5 × 30 g)','850047456700','Inuline, havervlokken, cashewnoten (12%), volkoren tarwevlokken, gepofte volkoren rijst, dadelstroop, tahin (hele sesam), zonnebloempitten, lijnzaad, pompoenpitten, gedroogde kokosvlokken (2,5%) [kokos, sulfiet (conserveermiddel)], glycerine, natuurlijk aroma (kokosextract), steviolglycosiden.',['Haver (gluten)','Tarwe (gluten)','Cashewnoten','Sesam','Sulfieten'],'Pecannoten, hazelnoten, walnoten, paranoten, macadamianoten, pistachenoten, pijnboompitten, amandelen, pinda’s, soja en mosterd.',carmitK,{warning:choking});
add(5,6,'Carmit Nature','Granola-repen pecan pie','Repen','150 g (5 × 30 g)','850047456694','Inuline, gepofte volkoren rijst, havervlokken, pecannoten (12%), cashewnoten (12%), pompoenpitten, dadelstroop, glycerine, geconcentreerd appelsap, specerij (kaneel), zout, natuurlijk aroma (karamelextract), tahin (hele sesam), steviolglycosiden.',['Haver (gluten)','Pecannoten','Cashewnoten','Sesam'],'Hazelnoten, walnoten, paranoten, macadamianoten, pistachenoten, pijnboompitten, amandelen, pinda’s, soja, tarwe en mosterd.',carmitK,{warning:choking});
add(7,8,'Carmit Nature','Granola-repen tahin & amandelen','Repen','150 g (5 × 30 g)','850047456724','Havervlokken, inuline, tahin (hele sesam), gepofte volkoren rijst, hele geroosterde amandelen (7%), dadelstroop, volkoren tarwevlokken, zonnebloempitten, lijnzaad, pompoenpitten, natuurlijk aroma (vanille-extract), steviolglycosiden.',['Haver (gluten)','Tarwe (gluten)','Amandelen','Sesam'],'Pecannoten, hazelnoten, cashewnoten, walnoten, paranoten, macadamianoten, pistachenoten, pijnboompitten, pinda’s, soja en mosterd.',carmitK,{warning:choking});
add(9,11,'Carmit Nature','Crunchy granola chocolade & hazelnoten','Granola','300 g','850047456755','Havermoutvlokken, inuline, pure chocolade (8%) [suiker, cacaomassa, cacaoboter, koolzaadlecithine, PGPR (emulgator), vanilline], hazelnoten (7,5%) (hele hazelnoten, hazelnootpasta), tahin (hele sesam), dadelstroop (dadels, suiker, citroenzuur), zonnebloempitten, gedroogde kokosvlokken [kokos, sulfiet (conserveermiddel)], zout, emulgator (koolzaadlecithine), steviolglycosiden.',['Haver (gluten)','Hazelnoten','Sesam','Sulfieten'],'Tarwe, pecannoten, cashewnoten, walnoten, paranoten, macadamianoten, pistachenoten, pijnboompitten, amandelen, pinda’s, soja en mosterd.',carmitK);
add(12,14,'Carmit Nature','Crunchy granola banaan & pecan','Granola','300 g','850047456748','Havermoutvlokken, dadelstroop, inuline, tahin (hele sesam), bananenchips (5%) (bananen, kokosolie, suiker), pecannoten (4%), zonnebloempitten, pompoenpitten, gedroogde kokosvlokken [kokos, sulfiet (conserveermiddel)], specerijen (kaneel), emulgator (raapzaadlecithine), zout, steviolglycosiden.',['Haver (gluten)','Pecannoten','Sesam','Sulfieten'],'Tarwe, hazelnoten, cashewnoten, walnoten, paranoten, macadamianoten, pistachenoten, pijnboompitten, amandelen, pinda’s, soja en mosterd.',carmitK);
add(15,17,'Carmit Nature','Crunchy granola cranberry & cashew','Granola','300 g','850047456762','Havermoutvlokken, inuline, tahin (hele sesam), cashewnoten (6%), veenbessen (5%) (veenbessen, appelconcentraat, zonnebloemolie), pompoenpitten, dadelstroop [dadels, suiker, citroenzuur (zuurteregelaar)], zonnebloempitten, gedroogde kokosvlokken [kokos, sulfiet (conserveermiddel)], specerijen (kaneel), zout, steviolglycosiden.',['Haver (gluten)','Cashewnoten','Sesam','Sulfieten'],'Tarwe, pecannoten, hazelnoten, walnoten, paranoten, macadamianoten, pistachenoten, pijnboompitten, amandelen, pinda’s, soja en mosterd.',carmitK);

add(18,19,'Shneider’s','Crêpes pannenkoekenmix','Bakmixen & desserts','170 g','194961004549','Tarwebloem, glucosestroop, eipoeder, eidooierpoeder, zout.',['Tarwe (gluten)','Ei'],'Andere glutenbevattende granen, melk en noten.','STAR-K (Parve)',{warning:'Eet geen rauw beslag.'});
add(20,22,'Shneider’s','Crème pâtissière banketbakkersroommix','Bakmixen & desserts','240 g (2 × 120 g)','194961004525','Suiker, zetmeel (maïs, aardappel), aroma’s, verdikkingsmiddel (xanthaangom), kleurstof (carotenen).',[],'Glutenbevattende granen, melk, ei, noten en soja.',null,{allergenNote:'Soja wordt alleen in de Nederlandse fabrieksvermelding genoemd.'});
add(23,25,'Shneider’s','Muffinmix','Bakmixen & desserts','','194961004532','Tarwebloem, suiker, rijsmiddelen (difosfaten, natriumcarbonaten), verdikkingsmiddel (xanthaangom), aroma.',['Tarwe (gluten)'],'Andere glutenbevattende granen, melk, ei, noten en soja.',null,{warning:'Eet geen rauw beslag.',allergenNote:'Soja wordt alleen in de Nederlandse fabrieksvermelding genoemd.'});
add(26,28,'Shneider’s','Crème brûlée mix','Bakmixen & desserts','','194961004518','Crèmemix: suiker, zetmeel (maïs, erwten), natuurlijk vanillearoma, eipoeder, geleermiddel (carrageen), kleurstoffen (kurkuma, paprika-extract), maltodextrine. Karamelmix: 28% karamelstukjes (suiker, glucosestroop).',['Ei'],'Glutenbevattende granen, melk, noten en soja.');
add(29,31,'Osem','Instantpudding vanille','Bakmixen & desserts','80 g','077544361003','Suiker, maltodextrine, maïszetmeel, zuurteregelaars (E450, E327, E263, E339), aroma’s, kleurstof (carotenen).',[],'Soja.');
add(32,34,'Osem','Instantpudding Franse vanille','Bakmixen & desserts','80 g','7290104501661','Maltodextrine, suiker, gemodificeerd zetmeel (E1422), zuurteregelaars (E450, E327, E263, E339), aroma’s, kleurstof (wortelextract), plantaardige vetten.',[],'Soja.');
add(35,37,'Osem','Instantpudding chocolade','Bakmixen & desserts','95 g','077544003958','Suiker, gemodificeerd tapiocazetmeel, gealkaliseerd cacaopoeder (12,5%), zuurteregelaars (E450, E263, E339).',[],'','OU-P (Parve; koosjer voor Pesach)');
add(38,40,'Osem','Jelly aardbei','Bakmixen & desserts','90 g','077544490000','Suiker, geleermiddel (E407), voedingszuren (E355, E297, E330), zuurteregelaars (E331, E263), maltodextrine, kleurstoffen (zwartewortelextract, kurkuma-extract), aroma’s, conserveermiddel (zwaveldioxide).',['Sulfieten'],'Soja.');
add(41,43,'Osem','Instantpudding dulce de leche','Bakmixen & desserts','84 g','7290100681015','Maltodextrine, suiker, zetmeel, zuurteregelaars (E450, E327, E263, E339), karamelsuiker, aroma’s, plantaardige vetten.',[],'Soja.');
const dateWarning = 'Kan dadelpitten of stukjes notendop bevatten.';
add(44,46,'The Date Bar','Dadelreep cashew & cranberry','Repen','37 g','890867000448','Medjooldadels, zonnebloempitten, cranberries (met appelconcentraat en zonnebloemolie), cashewnoten, hele sesamzaadjes, natuurlijke aroma’s.',['Cashewnoten','Sesam'],'Hazelnoten, amandelen, walnoten en pinda’s.','OU (Parve)',{warning:dateWarning});
add(47,49,'The Date Bar','Dadelreep walnoot','Repen','37 g','890867000431','Medjooldadels, rozijnen, walnoten, zonnebloempitten, hele sesamzaadjes, natuurlijke aroma’s.',['Walnoten','Sesam'],'Hazelnoten, amandelen, cashewnoten en pinda’s.','OU (Parve)',{warning:dateWarning});
add(50,51,'The Date Bar','Dadelreep banaan & walnoot','Repen','37 g',null,'Medjooldadels, walnoten, zonnebloempitten, gevriesdroogde bananen, sesamzaadjes, natuurlijke aroma’s.',['Walnoten','Sesam'],'Noten en pinda’s.','OU (Parve)');
add(53,54,'The Date Bar','Dadelreep kokos & hazelnoot','Repen','37 g',null,'Medjooldadels, kokos, rozijnen, hazelnoten, zonnebloempitten, natuurlijke aroma’s.',['Hazelnoten'],'Amandelen, walnoten, cashewnoten, pinda’s en sesam.','OU (Parve)',{warning:dateWarning});
add(55,57,'The Date Bar','Dadelreep pinda','Repen','37 g','890867000424','Medjooldadels, pinda’s, zonnebloempitten, rozijnen, natuurlijke aroma’s.',['Pinda’s'],'Hazelnoten, amandelen, walnoten, cashewnoten en sesam.','OU (Parve)',{warning:dateWarning});
const bitesWarning = 'Kan stukjes notendop bevatten. Jonge kinderen alleen onder toezicht van een volwassene laten eten.';
add(58,60,'Bar Bary','Bites dadel, amandel & kokos met ananassmaak','Dadelbites','55 g','890867000653','Medjooldadels, gemalen hazelnoten, gemalen cashewnoten, zonnebloempitten, gemalen amandelen, gemalen kokos, natuurlijke aroma’s.',['Hazelnoten','Cashewnoten','Amandelen'],'Andere noten, sesam en pinda’s.','OU (Parve)',{warning:bitesWarning});
add(61,63,'Bar Bary','Bites dadel, pecan & hazelnoot met bessensmaak','Dadelbites','55 g','890867000639','Medjooldadels, gemalen hazelnoten, zonnebloempitten, rozijnen, gemalen pecannoten, gemalen amandelen, natuurlijke aroma’s.',['Hazelnoten','Pecannoten','Amandelen'],'Andere noten, sesam en pinda’s.','OU (Parve)',{warning:bitesWarning});
add(64,66,'Bar Bary','Bites dadel, cashew & pistache','Dadelbites','55 g',null,'Medjooldadels, gemalen cashewnoten, zonnebloempitten, rozijnen, gemalen pistachenoten, hele sesamzaadjes, gemalen amandelen, natuurlijke aroma’s.',['Cashewnoten','Pistachenoten','Sesam','Amandelen'],'Andere noten en pinda’s.','OU (Parve)',{warning:bitesWarning});
add(67,69,'Bar Bary','Bites dadel, walnoot & banaan','Dadelbites','55 g','890867000646','Medjooldadels, gemalen walnoten, zonnebloempitten, hele sesamzaadjes, gevriesdroogde banaan, natuurlijke aroma’s.',['Walnoten','Sesam'],'Andere noten en pinda’s.','OU (Parve)',{warning:bitesWarning});
const schK='OU-D-P IRG Zürich (Chalav Yisrael)';
add(70,71,'Schmerling’s','Blanc witte chocolade zonder toegevoegde suiker','Chocoladetabletten','100 g','011835212001','Zoetstof (maltitol), cacaoboter, volle melkpoeder, emulgator (sojalecithine), aroma (karamel), vanille-extract.',['Melk','Soja'],'Hazelnoten en amandelen.','OU-D, IRG Zürich (Chalav Yisrael)',{warning:'Overmatig gebruik kan een laxerend effect hebben.'});
add(72,73,'Schmerling’s','Rosemarie Harmony witte chocolade met praliné','Chocoladetabletten','100 g','097643070248','Suiker, cacaoboter, volle melkpoeder, hazelnoten (14%), amandelen, cacaomassa, vanille-extract.',['Melk','Hazelnoten','Amandelen'],'Soja.',schK);
add(74,76,'Schmerling’s','Rosemarie Cappuccino','Chocoladetabletten','100 g','097643051445','Suiker, cacaoboter, volle melkpoeder, hazelnoten, cacaomassa, amandelen, koffiepoeder (2%), vanille-extract.',['Melk','Hazelnoten','Amandelen'],'Soja.',schK);
add(77,78,'Schmerling’s','Rosemarie Split nougat-praliné','Chocoladetabletten','100 g','097643084047','Suiker, cacaoboter, volle melkpoeder, hazelnoten (14%), amandelen, cacaomassa, vanille-extract.',['Melk','Hazelnoten','Amandelen'],'Soja.',schK);
add(79,81,'Schmerling’s','Ice Coffee witte chocolade met koffie','Chocoladetabletten','100 g','097643070446','Suiker, cacaoboter, volle melkpoeder, koffie (1,5%), vanille-extract.',['Melk'],'Hazelnoten, amandelen en soja.',schK,{allergenNote:'Het oorspronkelijke etiket noemt hazelnoten en amandelen als mogelijke sporen. De Nederlandse sticker noemt ze als aanwezige allergenen; deze afwijking is nog niet opgehelderd.',labelConflict:true});
add(82,83,'Schmerling’s','White Almond witte chocolade met amandelen','Chocoladetabletten','100 g','097643070040','Suiker, cacaoboter, volle melkpoeder, amandelen (8%), vanille-extract.',['Melk','Amandelen'],'Hazelnoten en soja.',schK);
add(84,85,'Schmerling’s','Choco Blanc witte chocolade','Chocoladetabletten','100 g','097643070149','Suiker, cacaoboter, volle melkpoeder, vanille-extract.',['Melk'],'Hazelnoten, amandelen en soja.',schK);
add(86,87,'Schmerling’s','Swiss Milk melkchocolade','Chocoladetabletten','100 g','097643069549','Suiker, cacaoboter, volle melkpoeder, cacaomassa, vanille-extract.',['Melk'],'Hazelnoten, amandelen en soja.',schK);
add(88,89,'Schmerling’s','Pure chocolade 72% cacao','Chocoladetabletten','100 g','097643044546','Cacaomassa, suiker, cacaoboter, cacaopoeder, vanille-extract.',[],'Hazelnoten, amandelen, melk en soja.','OU-P, IRG Zürich (Parve; koosjer voor Pesach)');
add(90,91,'Schmerling’s','Extra pure chocolade 85% cacao','Chocoladetabletten','100 g','097643044553','Cacaomassa, suiker, cacaopoeder, cacaoboter, vanille-extract.',[],'Hazelnoten, amandelen, melk en soja.','OU-P, IRG Zürich (Parve; koosjer voor Pesach)');
const eliteAll=['Melk','Amandelen','Hazelnoten','Soja'];
const eliteMay='Tarwe en gerst (gluten), pinda’s, pecannoten, ei en sesam.';
add(92,94,'Elite','Blondie witte karamelchocolade met roomvulling','Chocoladetabletten','100 g','7290112332158','Suiker, melkpoeder, cacaoboter, plantaardige oliën en vetten, melkbestanddelen in poedervorm, melkvet, voedingsvezels (inuline), emulgatoren (raapzaadlecithine, E476), vanilline.',eliteAll,eliteMay,null,{allergenNote:'Amandelen, hazelnoten en soja worden op het etiket als aanwezige allergenen vermeld.'});
add(95,97,'Elite','Blondie witte karamelchocolade met hazelnootcrème','Chocoladetabletten','100 g','7290110564353','Suiker, cacaoboter, melkpoeder, plantaardige oliën en vetten, sojameel, voedingsvezels (inuline), melkbestanddelen in poedervorm, hazelnootpasta (4%), cacaomassa, melkvet, emulgatoren (raapzaadlecithine, E476), vanilline, zout.',eliteAll,eliteMay);
add(98,99,'Elite','Melkchocolade met nougatcrème','Chocoladetabletten','100 g','7290104724718','Suiker, melkpoeder, hazelnootpasta (13%), cacaoboter, cacaomassa, plantaardige oliën en vetten, sojameel, melkvet, emulgatoren (raapzaadlecithine, E476), vanilline.',eliteAll,eliteMay);
add(100,101,'Elite','Melkchocolade met melkcrème','Chocoladetabletten','100 g','7290003903955','Suiker, melkpoeder, melkbestanddelen in poedervorm, plantaardige oliën en vetten, cacaoboter, cacaomassa, melkvet, emulgatoren (raapzaadlecithine, E476), aroma’s.',eliteAll,eliteMay,null,{allergenNote:'De oorspronkelijke verpakking noemt melk, amandelen, hazelnoten en soja. De Nederlandse sticker vermeldt een afwijkende receptuur; de bovenstaande ingrediënten zijn vertaald van het oorspronkelijke etiket.',labelConflict:true});
add(102,103,'Elite','Witte chocolade met glutenvrije cacaokoekjes','Chocoladetabletten','100 g','7290119382576','Suiker, cacaoboter, melkpoeder, cacaokoekjes (10%) [maïsmeel, aardappelzetmeel, suiker, plantaardige oliën en vetten, vetarm cacaopoeder, dextrosemonohydraat, tapiocazetmeel, zout, aroma’s, rijsmiddelen (E500ii, E503ii)], lactose, melkvet, emulgatoren (raapzaadlecithine, E476), vanilline.',['Melk'],'Pinda’s, amandelen, hazelnoten, cashewnoten, walnoten, pistachenoten, pecannoten, ei, soja en sesam.');
add(104,105,'Elite','Pesek Zman Classic','Chocoladerepen','45 g',null,'Melkchocolade [suiker, cacaoboter, magere melkpoeder, cacaomassa, melkvet, raapzaadlecithine, PGPR, kunstmatig aroma (vanilline)], suiker, hazelnootpasta, plantaardige vetten en oliën (palm), tarwebloem, sojameel, cacaomassa, raapzaadlecithine, rijsmiddelen (natriumbicarbonaat, ammoniumbicarbonaat), zout, enzym (proteïnase).',['Melk','Hazelnoten','Tarwe (gluten)','Soja'],'Pinda’s, andere noten, ei en sesam.');
add(106,109,'Elite','Pesek Zman wafel & hazelnootcrème','Chocoladerepen','52 g','815871010184','Melkchocolade [suiker, cacaoboter, magere melkpoeder, cacaomassa, melkvet, raapzaadlecithine, PGPR, kunstmatig aroma (vanilline)], suiker, hazelnootpasta, plantaardige vetten en oliën (palm), tarwebloem, sojameel, magere melkpoeder, wei (melk), cacaomassa, melkvet, raapzaadlecithine, rijsmiddelen (natriumbicarbonaat, ammoniumbicarbonaat), kunstmatig aroma, zout, enzym (proteïnase).',['Melk','Hazelnoten','Tarwe (gluten)','Soja'],'Pinda’s, andere noten, ei en sesam.');
add(110,112,'Elite','Taami chocolade, karamel & gepofte rijst','Chocoladerepen','40 g','72917367','Melkchocolade (34%), suiker, gepofte rijst (12%) (rijst, suiker, zout), plantaardige oliën en vetten, glucosestroop, melkbestanddelen in poedervorm, hazelnootpasta (4%), cacaomassa, tarwebloem, water, bevochtigingsmiddel (glycerol), emulgator (raapzaadlecithine), zout, vanilline.',['Melk','Tarwe (gluten)'],'Pinda’s, amandelen, hazelnoten, pecannoten, ei, soja, gerst (gluten) en sesam.','OU-D (Chalav Yisrael)',{allergenNote:'Hazelnootpasta staat in de ingrediënten; hazelnoten worden daarom ook als aanwezig beschouwd.'});
products.at(-1).allergens.push('Hazelnoten');
add(113,115,'Elite','Chocolate Log melkchocoladereep','Chocoladerepen','25 g','815871015868','Suiker, cacaoboter, magere melkpoeder, cacaomassa, melkvet, raapzaadlecithine, kunstmatig aroma (vanilline).',['Melk'],'Pinda’s, noten, ei, soja en sesam.');
add(116,117,'Elite','Kranch biscuit & hazelnootcrème','Chocoladetabletten','100 g','7290119384068','Melkchocolade, biscuit (tarwegluten; verdere samenstelling niet leesbaar), suiker, hazelnootpuree (10,5%), plantaardige oliën en vetten, cacaomassa, emulgator (koolzaadlecithine).',['Melk','Tarwe (gluten)','Hazelnoten'],'Pecannoten, sesam, pinda’s, andere noten en ei.',null,{allergenNote:'De sticker dekt het oorspronkelijke etiket af. De volledige samenstelling van de chocolade en het biscuit is nog niet bevestigd.',ingredientsIncomplete:true});
const wowK='Badatz Edah HaChareidis (Melk)';
const wowMay='Tarwe (gluten), ei, sesam, pinda’s, amandelen, hazelnoten, cashewnoten, pecannoten, pistachenoten, walnoten en kokos.';
const wowMilk='Melkchocolade [suiker, cacaoboter, volle melkpoeder, cacaomassa, emulgatoren (sojalecithine, E476), vanilline]';
add(118,120,'WOW','Graanbolletjes met melkchocolade','Chocoladesnacks','50 g','7290019779315',wowMilk+', witte chocolade [suiker, cacaoboter, volle melkpoeder, emulgatoren (sojalecithine, E471), vanilline], graanbolletjes (maïsmeel, suiker, melkpoeder, zout), stabilisator (acaciagom), suiker.',['Melk','Soja'],wowMay,wowK);
add(121,122,'WOW','Cornflakes met melkchocolade','Chocoladesnacks','50 g','7290019779278',wowMilk+', cornflakes [maïsmeel, suiker, zout, zuurteregelaar (E339iii)], stabilisator (arabische gom), suiker.',['Melk','Soja'],wowMay,wowK);
add(123,124,'WOW','Koekjes met melkchocolade','Chocoladesnacks','50 g','7290019779292',wowMilk+', koekjes met botersmaak [tarwebloem, suiker, plantaardige oliën en vetten, zout, aroma’s, dextrose, antioxidant (rozemarijnextract)], stabilisator (acaciagom), suiker.',['Melk','Soja','Tarwe (gluten)'],'Ei, sesam, pinda’s, amandelen, hazelnoten, cashewnoten, pecannoten, pistachenoten, walnoten en kokos.',wowK);
add(125,126,'WOW','Graanbolletjes met melk- en witte chocolade','Chocoladesnacks','50 g','7290019779322',wowMilk+', witte chocolade [suiker, cacaoboter, volle melkpoeder, emulgatoren (sojalecithine, E471), vanilline], graanbolletjes [maïsmeel, suiker, zout], stabilisator (acaciagom), suiker.',['Melk','Soja'],wowMay,wowK);
add(127,129,'WOW','Wafelrolletjes met notencrème en melkchocolade','Chocoladesnacks','50 g','7290019779285',wowMilk+', miniwafelrolletjes gevuld met notencrème [suiker, tarwebloem, plantaardige oliën en vetten, noten (9%) (hazelnoten en amandelen), sojabloem, cacaopoeder, dextrose, emulgator (sojalecithine), kleurstof (karamel), zout, antioxidant (rozemarijnextract), aroma’s], stabilisator (acaciagom), suiker.',['Melk','Soja','Tarwe (gluten)','Hazelnoten','Amandelen'],'Ei, sesam, pinda’s, cashewnoten, pecannoten, pistachenoten, walnoten en kokos.',wowK);
add(130,131,'Elisha','Cacaopoeder','Bakingrediënten','','5425000533979','Cacaopoeder.',[],'','Machsike Hadas Antwerpen (Parve)');
add(132,133,'Alprose','Swiss Baking Chocolate pure bakchocolade','Bakingrediënten','300 g','712963000286','Cacaomassa, suiker, cacaoboter, hazelnoten, kunstmatig aroma (vanille). Cacaobestanddelen: minimaal 50%.',['Hazelnoten'],'Melk, soja, tarwe (gluten) en andere noten.','OU-P (Parve; koosjer voor Pesach)');
add(134,134,'Elisha','Marsepein 50/50 met chocolade','Marsepein','40 g','5425000532026','Suiker (50%), amandelen (50%), chocolade, conserveermiddel (E202).',['Amandelen'],'','Machsike Hadas Antwerpen (Parve)',{ingredientsIncomplete:true,allergenNote:'De samenstelling van de chocolade en de verhouding van de coating zijn niet uitgewerkt op het etiket.'});
add(135,135,'Elisha','Marsepein 50/50 naturel','Marsepein','40 g','5425000533344','Suiker (50%), amandelen (50%), conserveermiddel (E202).',['Amandelen'],'','Machsike Hadas Antwerpen (Parve)');
add(136,138,'Shneider’s','The Good Life plantaardige kloproom','Room & mascarpone','1.000 ml','194961000923','Water, niet-gehydrogeneerde plantaardige vetten (22%) (kokosolie, palmpitolie, cacaoboter), suiker (11%), soja-eiwitisolaat (0,5%), stabilisatoren [sorbitolen (E420), hydroxypropylcellulose (E463), carboxymethylcellulose (E466), natriumfosfaat (E339)], emulgatoren [diacetylwijnsteenzuuresters van mono- en diglyceriden (E472e), polyoxyethyleensorbitaanmono-oleaat (E433), melkzuuresters van mono- en diglyceriden (E472b)], zout, aroma’s, kleurstof (E160a).',['Soja'],'',null);
add(139,140,'Shneider’s','The Good Life plantaardige spuitroom','Room & mascarpone','250 g',null,'Water, niet-gehydrogeneerde plantaardige vetten (22%) (kokosolie, palmpitolie, cacaoboter), suiker (11%), soja-eiwit (0,5%), stabilisatoren [sorbitol (E420), cellulose (E460), carboxymethylcellulose (E466)], emulgatoren [diacetylwijnsteenzuuresters van mono- en diglyceriden (E472e), polyoxyethyleensorbitaanmono-oleaat (E433)], zout, aroma’s, drijfgas (distikstofoxide, E942).',['Soja'],'','STAR-K (Parve)');
add(141,143,'Sterilgarda','Mascarpone UHT','Room & mascarpone','500 g','8002795002254','Melkroom, zuurteregelaar (melkzuur).',['Melk'],'','Dayan Yirmiyahu Cohen, Parijs (Chalav Yisrael; koosjer voor Pesach)');
add(144,145,'Shneider’s','Chocoladefondue puur 56% cacao','Bakingrediënten','300 g','194961005003','Cacaomassa, suiker, cacaoboter, emulgator (sojalecithine), natuurlijk vanillearoma.',['Soja'],'Noten en melk.','Parve');
add(146,147,'Shneider’s','Chocoladefondue melk','Bakingrediënten','300 g','194961005072','Cacaoboter, cacaomassa, suiker, volle melkpoeder, emulgator (sojalecithine).',['Melk','Soja'],'Noten.','Chalav Yisrael');
add(148,150,'Gross & Co','Chocolate Squares munt','Chocoladesnacks','200 g','712963003744','Suiker, cacaomassa, glucosestroop, cacaoboter, bevochtigingsmiddel (invertase), emulgator (sojalecithine), pepermuntolie, zout, voedingszuur (citroenzuur).',['Soja'],'Melk, glutenbevattende granen, noten en pinda’s.');
add(151,153,'Gross & Co','Chocolate Squares sinaasappel & munt','Chocoladesnacks','200 g','712963003751','Suiker, cacaomassa, glucosestroop, cacaoboter, bevochtigingsmiddel (invertase), emulgator (sojalecithine), sinaasappelaroma, pepermuntolie, zout, voedingszuur (citroenzuur).',['Soja'],'Melk, glutenbevattende granen, noten en pinda’s.');
add(154,157,'Gross & Co','Chocolate Squares framboos','Chocoladesnacks','200 g','712963004932','Suiker, cacaomassa, glucosestroop, cacaoboter, water, natuurlijk aroma, invertsuikerstroop, kleurstof (vlierbessensapconcentraat), emulgator (sojalecithine), bevochtigingsmiddel (invertase), voedingszuur (citroenzuur), geleermiddel (agar), zout.',['Soja'],'Melk, glutenbevattende granen, pinda’s en noten.');
// Extra artikel en schapvolgorde bevestigd door de gebruiker (160.jpg).
for (const p of products) {
  p.name = p.name.replace('Granola-repen', 'Granola repen');
  const photo = parseInt(p.sourcePhotos[0]);
  const weights = {23:'155 g',26:'105 g',130:'250 g'};
  if (weights[photo]) { p.variant = weights[photo]; p.productInfo.Inhoud = weights[photo]; }
  if (photo === 139) p.ean = '194961000930';
  if (photo === 106) p.name = 'Pesek Zman Big Bite wafel & hazelnootcrème';
}
products.push({id:63,brand:'Schmerling’s',name:'Orange Noir pure chocolade met sinaasappel & amandelen',category:'Chocoladetabletten',variant:'100 g',ean:'097643070057',ingredients:'Suiker, cacaomassa, cacaoboter, amandelen (8%), aroma’s (sinaasappel, vanilline). Cacaobestanddelen: minimaal 55%.',allergens:['Amandelen'],mayContain:'Hazelnoten.',kosher:'Parve',image:'images/product-orange-noir-user.png',sourcePhotos:[],productInfo:{Inhoud:'100 g'},allergenNote:'Productinformatie uit een online productvermelding; het etiket van de winkelverpakking is nog niet aangeleverd.',dataSourceUrl:'https://www.instacart.ca/products/17459788-schmerling-s-finest-swiss-dark-chocolate-orange-noir-3-5-oz'});
const shelfOrder=[1,5,3,7,9,12,15,18,20,23,26,29,32,35,38,41,44,47,50,53,55,58,61,64,67,70,72,74,77,79,'orange',82,84,86,88,90,92,95,98,100,102,104,106,110,113,116,118,121,123,125,127,148,151,154,130,132,134,135,136,139,141,144,146];
// Door de gebruiker bevestigde uniforme hechshervermelding voor Schmerling.
for (const p of products) {
  if (p.brand === 'Schmerling’s') p.kosher = schK;
  if (p.sourcePhotos[0] === '132.jpg') p.kosher = 'OU-P';
  if (p.sourcePhotos[0] === '141.jpg') p.kosher = 'Dayan Yirmiyahu Cohen Parijs (Chalav Yisrael)';
  if (p.sourcePhotos[0] === '134.jpg') delete p.allergenNote;
  if (p.sourcePhotos[0] === '136.jpg') { p.variant = '1 L'; p.productInfo.Inhoud = '1 L'; }
  if (p.brand === 'Elite') p.kosher = 'Badatz Edah Hachareidis of Jerusalem';
  if (p.brand === 'Shneider’s') p.kosher = p.sourcePhotos[0] === '146.jpg' ? 'STAR-K' : 'STAR-K (Parve)';
  if (['29.jpg','32.jpg','41.jpg'].includes(p.sourcePhotos[0])) p.kosher = 'Badatz Edah Hachareidis of Jerusalem (Parve)';
  if (p.sourcePhotos[0] === '79.jpg') {
    p.allergenNote = 'Ingrediënten en allergenen overgenomen van het oorspronkelijke etiket.';
    delete p.labelConflict;
  }
}
const shelfKey = p => p.id===63?'orange':parseInt(p.sourcePhotos[0]);
products.sort((a,b)=>shelfOrder.indexOf(shelfKey(a))-shelfOrder.indexOf(shelfKey(b)));
// De titel onder iedere foto is Nederlands; originele namen blijven vindbaar.
const dutchNames={
1:'Granola repen met noten en cranberry',3:'Granola repen met kokos en cashewnoten',5:'Granola repen met pecantaartsmaak',7:'Granola repen met tahin en amandelen',
9:'Krokante granola met chocolade en hazelnoten',12:'Krokante granola met banaan en pecannoten',15:'Krokante granola met cranberry en cashewnoten',
18:'Pannenkoekenmix',20:'Mix voor banketbakkersroom',23:'Muffinmix',26:'Mix voor roomdessert met karamellaag',
29:'Instantpudding met vanillesmaak',32:'Instantpudding met Franse vanillesmaak',35:'Instantpudding met chocoladesmaak',38:'Geleipudding met aardbeiensmaak',41:'Instantpudding met melkkaramelsmaak',
58:'Dadelhapjes met amandel, kokos en ananassmaak',61:'Dadelhapjes met pecannoten, hazelnoten en bessensmaak',64:'Dadelhapjes met cashewnoten en pistachenoten',67:'Dadelhapjes met walnoten en banaan',
70:'Witte chocolade zonder toegevoegde suiker',72:'Witte chocolade met pralinévulling',74:'Chocolade met koffiepralinévulling',77:'Chocolade met nougat-pralinévulling',79:'Witte chocolade met koffie',82:'Witte chocolade met amandelen',84:'Witte chocolade',86:'Zwitserse melkchocolade',88:'Pure chocolade met 72% cacao',90:'Extra pure chocolade met 85% cacao',
92:'Witte karamelchocolade met roomvulling',95:'Witte karamelchocolade met hazelnootcrème',104:'Wafelreep met melkchocolade en hazelnootcrème',106:'Grote wafelreep met melkchocolade en hazelnootcrème',110:'Chocoladereep met karamel en gepofte rijst',113:'Melkchocoladereep',116:'Melkchocolade met biscuit en hazelnootcrème',
132:'Zwitserse pure bakchocolade',136:'Plantaardige kloproom',139:'Plantaardige spuitroom',141:'Mascarpone',148:'Pure chocoladevierkantjes met muntvulling',151:'Pure chocoladevierkantjes met sinaasappel- en muntvulling',154:'Pure chocoladevierkantjes met frambozenvulling'
};
for(const p of products){p.searchName=p.name; const n=parseInt(p.sourcePhotos[0]);if(dutchNames[n])p.name=dutchNames[n];if(p.id===63)p.name='Pure chocolade met sinaasappel en amandelen';}
const manifestPath=path.join(__dirname,'image-sources.json');
if(fs.existsSync(manifestPath)){
  const images=JSON.parse(fs.readFileSync(manifestPath,'utf8'));
  for(const p of products){const source=images[p.sourcePhotos[0] || 'orange-noir']; if(source){p.image=source.localImage;p.sourceUrl=source.page;if(source.imagePresentation)p.imagePresentation=source.imagePresentation;if(source.imageEdited)p.imageEdited=true;}}
}
fs.writeFileSync(path.join(__dirname,'products.js'),'window.KPI_PRODUCTS = '+JSON.stringify(products,null,2)+';\n');
